# Generated by Django 4.1 on 2022-08-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_student_address_student_country_student_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
